### ISSUE TITLE
Too many spaces between Dated Journal Entries

### ISSUE THREAD

**Issue by LoveJungle** [Will-Renius/DatedJournalEntry#2]
When I add a new date, it always puts it 4 spaces down on the page. This is too far down imo. I should only go down one or two spaces. Is there a way to make this easily programmable for the lay person who doesn't code?

**Comment by Will-Renius** [comment]
I'm not able to replicate this issue, what are your settings? The addon is programmed to add a date at the bottom of your document and add only 1 new line to begin typeing. Are you adding 4 new lines at the end of your previous entry?
