### ISSUE TITLE
New Entry is Always Right Justified

### ISSUE THREAD

**Issue by wayneholly** [Will-Renius/DatedJournalEntry#3]
Every time I add a new dated entry, it starts right justified. I have tried every setting I can find to set left justify as the default. Any suggestions?

**Comment by Will-Renius** [comment]
Google docs maintains style adjustments per each heading level. When creating a new entry it starts a s Normal Text style, perhaps you've adjusted your normal style to default to right-justified. Select some left justfied text, where you see heading you can click the arrow and select 'Update Normal Text To Match"

![image](https://user-images.githubusercontent.com/11193373/80961405-eb65ef80-8dd8-11ea-891e-4f85a4c4dbf5.png)

**Comment by wayneholly** [comment]
Thanks! That did the job.

*Stay safe out there. People are counting on and care about you. *
*#allinillinois*

Wayne Holly
[image: email] wayne.holly@gmail.com

[image: cloudHQ]
<https://chrome.google.com/webstore/detail/free-email-tracker/nknojfclnachdkpdkjbbhbkgpnladhnj>
Powered
by
cloudHQ
<https://chrome.google.com/webstore/detail/free-email-tracker/nknojfclnachdkpdkjbbhbkgpnladhnj>
